Added nicer error message when a module fails to build
git-svn-id: https://znc.svn.sourceforge.net/svnroot/znc/trunk@128 726aef4b-f618-498e-8847-2d620e286838

diff --git a/znc-buildmod b/znc-buildmod
--- a/znc-buildmod
+++ b/znc-buildmod
@@ -25,7 +25,8 @@ do
 		echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[31m!! \033[34m]"
 	else
 		echo -e " \033[1m\033[32m*\033[39m\033[22m Building ${MOD}.so... "
-		(g++ ${CXXFLAGS} ${INCLUDES} ${LIBS} -shared -o ${MOD}.so ${FILE} && echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[32mok \033[34m]") || echo "[Error]"
+		(g++ ${CXXFLAGS} ${INCLUDES} ${LIBS} -shared -o ${MOD}.so ${FILE} && echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[32mok \033[34m]") \
+			|| (echo -e " \033[1m\033[31m*\033[39m\033[22m Error while building ${MOD}.so" && echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[31m!! \033[34m]")
 	fi
 done
 
