Close color and bold 'tags'
git-svn-id: https://znc.svn.sourceforge.net/svnroot/znc/trunk@137 726aef4b-f618-498e-8847-2d620e286838

diff --git a/znc-buildmod b/znc-buildmod
--- a/znc-buildmod
+++ b/znc-buildmod
@@ -11,7 +11,7 @@ LIBS=`znc-config --libs`
 
 if test ! -d ${INCLUDES:2}; then
 	echo -e " \033[1m\033[31m*\033[39m\033[22m Unable to find znc include dir [${INCLUDES:2}], please (re)install znc."
-	echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[31m!! \033[34m]"
+	echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[31m!! \033[34m]\033[39m\033[22m"
 	exit 1
 fi
 
@@ -22,11 +22,11 @@ do
 
 	if test ! -f ${FILE}; then
 		echo -e " \033[1m\033[31m*\033[39m\033[22m Could not find ${MOD}.so... "
-		echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[31m!! \033[34m]"
+		echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[31m!! \033[34m]\033[39m\033[22m"
 	else
 		echo -e " \033[1m\033[32m*\033[39m\033[22m Building ${MOD}.so... "
-		(g++ ${CXXFLAGS} ${INCLUDES} ${LIBS} -shared -o ${MOD}.so ${FILE} && echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[32mok \033[34m]") \
-			|| (echo -e " \033[1m\033[31m*\033[39m\033[22m Error while building ${MOD}.so" && echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[31m!! \033[34m]")
+		(g++ ${CXXFLAGS} ${INCLUDES} ${LIBS} -shared -o ${MOD}.so ${FILE} && echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[32mok \033[34m]\033[39m\033[22m") \
+			|| (echo -e " \033[1m\033[31m*\033[39m\033[22m Error while building ${MOD}.so" && echo -e "\b\b\b\b\b\b\033[1m\033[34m[ \033[31m!! \033[34m]\033[39m\033[22m")
 	fi
 done
 
